version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:361132770001:task-definition/srini-task:6","
        LoadBalancerInfo:
          ContainerName: "Srini-container"
          ContainerPort: 8080
